# Generated by Qodo Gen

import pytest

from gen_inroom_rtss import img_stack_displacement


class TestImgStackDisplacement:
    # Calculates displacement correctly for valid orientation and position inputs
    def test_valid_orientation_and_position(self):
        orientation = ["1.0", "0.0", "0.0", "0.0", "1.0", "0.0"]
        position = ["0.0", "0.0", "1.0"]
        expected_displacement = 1.0
        result = img_stack_displacement(orientation, position)
        assert result == expected_displacement

    # Handles empty or incomplete orientation and position lists gracefully
    def test_empty_or_incomplete_lists(self):
        with pytest.raises(IndexError):
            img_stack_displacement([], [])
        with pytest.raises(IndexError):
            img_stack_displacement(["1.0", "0.0"], ["0.0"])
